apiVersion: apps/v1
kind: Deployment
metadata:
  name: winningresult
  labels:
    app: winningresult
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winningresult
  template:
    metadata:
      labels:
        app: winningresult
    spec:
      containers:
        - name: winningresult
          image: "username/winningresult:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
