---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplyplan
  labels:
    app: supplyplan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplyplan
  template:
    metadata:
      labels:
        app: supplyplan
    spec:
      containers:
        - name: supplyplan
          image: username/supplyplan:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt
  labels:
    app: receipt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt
  template:
    metadata:
      labels:
        app: receipt
    spec:
      containers:
        - name: receipt
          image: username/receipt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: username/notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: winningresult
  labels:
    app: winningresult
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winningresult
  template:
    metadata:
      labels:
        app: winningresult
    spec:
      containers:
        - name: winningresult
          image: username/winningresult:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resident
  labels:
    app: resident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resident
  template:
    metadata:
      labels:
        app: resident
    spec:
      containers:
        - name: resident
          image: username/resident:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract
  labels:
    app: contract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract
  template:
    metadata:
      labels:
        app: contract
    spec:
      containers:
        - name: contract
          image: username/contract:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: supplyplan
  labels:
    app: supplyplan
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: supplyplan


---


apiVersion: v1
kind: Service
metadata:
  name: receipt
  labels:
    app: receipt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: receipt


---


apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notification


---


apiVersion: v1
kind: Service
metadata:
  name: winningresult
  labels:
    app: winningresult
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: winningresult


---


apiVersion: v1
kind: Service
metadata:
  name: resident
  labels:
    app: resident
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: resident


---


apiVersion: v1
kind: Service
metadata:
  name: contract
  labels:
    app: contract
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: contract

