apiVersion: apps/v1
kind: Deployment
metadata:
  name: resident
  labels:
    app: resident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resident
  template:
    metadata:
      labels:
        app: resident
    spec:
      containers:
        - name: resident
          image: "username/resident:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
